SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `Relation`;
SET foreign_key_checks = 1;
CREATE TABLE `Relation` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idAccount` bigint(20) UNSIGNED NOT NULL,
  `idFamily` bigint(20) UNSIGNED NOT NULL,
  `type` enum('FATHER',
			  'MOTHER',
              'BROTHER',
              'SISTER',
              'GRAND_FATHER',
              'GRAND_MOTHER',
              'AUNT','UNCLE',
              'DAUGHTER','SON',
              'STEP_FATHER',
              'STEP_MOTHER',
              'FOSTER_PARENT',
              'FOSTER_FATHER',
              'FOSTER_MOTHER',
              'STEP_SON',
              'STEP_DAUGHTER',
              'COUSIN',
              'NEICE',
              'NEPHEW',
              'FRIEND',
              'FAMILY_FRIEND',
              'GIRL_FRIEND',
              'BOY_FRIEND',
              'FIANCE',
              'FIANCEE') NOT NULL,
  `idConsumer` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`idAccount`) REFERENCES `Account`(id),
  FOREIGN KEY (`idFamily`) REFERENCES `Family`(id),
  FOREIGN KEY (`idConsumer`) REFERENCES `Consumer`(id)
)